# Пользователи
## Создать нового пользователя

POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Plato",
  "email": "plato@mail.com",
  "password": "papqaqaq",
  "isPro": false,
  "avatar": "string"
}

###
## Авторизация пользователя

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "plato@mail.com",
  "password": "papqaqaq"
}

###

## Отправить изображение

POST http://localhost:3000/users/67cb46ef04311508baa02ebf/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\Дмитрий\Desktop\mangal.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:3000/users/authCheck HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InBsYXRvQG1haWwuY29tIiwibmFtZSI6IlBsYXRvIiwiaWQiOiI2N2Q0NzMwZjVmNjc1ZDc1ZmY0ZWRlNGUiLCJpYXQiOjE3NDE5Nzc1ODEsImV4cCI6MTc0MjE1MDM4MX0.FxzGEY6eZhePp0JUtnawKwCF60j1cL5jXKPkOKxyYjU

##
