# Пользователи
## Создать нового пользователя

POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "67c73ae2be6a11f4f1c09d8f",
  "email": "67c13ae2be6a51f4f1c09d8f",
  "password": "string",
  "isPro": false,
  "avatar": "string"
}

###
## Авторизация пользователя

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "string",
  "password": "string"
}

###

## Проверка состояния пользователя

GET http://localhost:3000/users/login/?userId=67c73ae2be6a51f4f1c09d8f HTTP/1.1
Content-Type: application/json

###

## Конец сессии пользователя

POST http://localhost:3000/users/logout HTTP/1.1
Content-Type: application/json

{
  "email": "string"
}

###

###

## Отправить изображение

POST http://localhost:3000/users/67cb46ef04311508baa02ebf/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\Дмитрий\Desktop\mangal.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
